import type { Metadata } from 'next';
import { Geist, Geist_Mono, Titillium_Web } from 'next/font/google';
import './globals.css';
import 'bootstrap-italia/dist/css/bootstrap-italia.min.css';
import './mobile-nav.css';
import { BrandingProvider } from '@/components/BrandingProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const titillium = Titillium_Web({
  variable: '--font-titillium',
  subsets: ['latin'],
  weight: ['400', '600', '700'], // optional: choose the weights you need
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${titillium.variable}`}>
        <BrandingProvider>
          {children}
        </BrandingProvider>
      </body>
    </html>
  );
}
